apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcpdevops
  template:
    metadata:
      labels:
        app: gcpdevops
    spec:
      containers:
        - name: gcpdevops
          image: us-central1-docker.pkg.dev/prj-mrdn-retail-dev/gcp-artifact-registry/gcpdevops:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
