apiVersion: v1
kind: Service
metadata:
  name: gcpdevops-service
  namespace: gcp-kodecloud-prod-namespace
spec:
  type: LoadBalancer
  selector:
    app: gcpdevops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
